### ISSUE TITLE
can I build this source for gt-i9300i?

### ISSUE THREAD

**Issue by amir-hossein-zarei** [S3NEO/android_kernel_samsung_s3ve3g#8]
can I build this source for gt-i9300i?
and how?

**Comment by PythonLimited** [comment]
Yes

**Comment by amir-hossein-zarei** [comment]
Is this gonna have duel sim problem and etc?

**Comment by PythonLimited** [comment]
Well the kernel doesn't matter for dual sim. The blobs do

**Comment by Amirhz9479** [comment]
ok, I understand this is a new question but if I want to build from the source, what branch and commands I have to use?
